name: MLflow CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  train-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: apple-quality-mlflow
          environment-file: MLProject/conda.yaml
          auto-activate-base: false

      - name: Verify Environment
        shell: bash -el {0}
        run: |
          python --version
          conda info
          pip list

      - name: Run MLflow Project
        shell: bash -el {0}
        run: |
          cd MLProject
          mlflow run . --env-manager local

      - name: Upload Training Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: |
            MLProject/artifacts
          if-no-files-found: warn

      - name: Save Artifacts to Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name ${{ secrets.username }}
          git config --global user.email ${{ secrets.email }}

          git add MLProject/artifacts

          git diff --staged --quiet || \
          git commit -m "Update ML artifacts"

          git push origin main

      - name: Get Latest Run ID
        shell: bash -el {0}
        run: |
          cd MLProject

          echo "===== DEBUG ====="
          find mlruns -type d
          echo "================="

          RUN_ID=$(find mlruns/0 -mindepth 1 -maxdepth 1 -type d | xargs -I {} basename {} | grep -E '^[a-z0-9]{32}$' | sort | tail -n 1)

          echo "RUN_ID=$RUN_ID"
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker Model
        shell: bash -el {0}
        run: |

          cd MLProject

          echo "Building from run: $RUN_ID"

          which mlflow

          mlflow models build-docker \
            --model-uri "runs:/$RUN_ID/model" \
            --name "apple-quality-model"

      - name: Tag Docker Image
        run: |

          docker tag \
            apple-quality-model \
            ${{ secrets.DOCKER_HUB_USERNAME }}/apple-quality-model:latest

      - name: Push Docker Image
        run: |

          docker push \
          ${{ secrets.DOCKER_HUB_USERNAME }}/apple-quality-model:latest

      - name: Finish Pipeline
        run: |
          echo "=================================="
          echo "Training completed successfully"
          echo "Artifacts uploaded"
          echo "Google Drive uploaded"
          echo "Docker image pushed"
          echo "=================================="